commerce_paystack.settings:
  type: config_object
  label: 'Commerce Paystack settings'
  mapping:
    secret_key:
      type: string
      label: 'Secret Key'
    public_key:
      type: string
      label: 'Public Key'
    currency_code:
      type: string
      label: 'Currency Code'
